NumPy 
https://numpy.org/
voce trabalha com ARRAS,que sao mais rapidas e mas perfomatica que lista
ARRAYS : sao estruturas de dados que guardam itens do mesmo tipo(diferentes das lista)

In [4]:
#como importar 
import numpy as np

In [5]:
teste=[1,2,4,5]
teste_2= [2,4,5,6]
calculo= teste+teste_2
print(calculo)

[1, 2, 4, 5, 2, 4, 5, 6]


In [6]:
teste_array = np.array(calculo)                                                                    
print(teste_array)

[1 2 4 5 2 4 5 6]


In [8]:
a = np.arange(15).reshape(3,5)

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
#verificar  as dimensao desse array
a.ndim

2

In [11]:
#verificar forma do array
a.shape #ou sej nese exemplo ele tem 3 linhas e 5 colunnas (3,5)

(3, 5)

In [12]:
#tipo de dados 
a.dtype

dtype('int64')

In [14]:
#buscar a primeira linha 
a[1]

array([5, 6, 7, 8, 9])

In [15]:
#na primeira linha busacando elemmento
a[0][3]

3

In [16]:
#buscar o elemento de indice 1 e 3 (incluindo o 3) na primeira linha 
a[0][1:4]

array([1, 2, 3])

In [19]:
#buscar apenas valor maior 5 
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
dados = np.arange(6).reshape(2,3)
dados

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
#somando todos os valores do array
dados.sum()

15

In [23]:
#somando  apenas valores da linha
dados.sum(axis=1)

array([ 3, 12])

In [24]:
#dados acumulados linha 
dados.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [25]:
#soma das coluna 
dados.sum(axis=0)


array([3, 5, 7])

In [26]:
# como somar toda array por 1 
dados +1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#verificar o menor valor do array 
dados.min()

0

In [31]:
#verificar o max valor do array 
dados.max()

5

In [32]:
#verificar o menor valor do array  coluna
dados.min(axis=0)

array([0, 1, 2])

In [33]:
#verificar o menor valor do array  linha
dados.min(axis=1)

array([0, 3])

In [34]:
# media
dados.mean()

2.5